### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by Perni1984** [OskarAhl/Lighthouse-github-action#5]
Hi @OskarAhl,

we are interested in using your code or parts of your code in our own github actions, but unfortunately I couldn't find any licensing information in the github repository. Could you kindly let me know which license you intend to have for you publicly shared code?

Thanks!

Christoph

**Comment by OskarAhl** [comment]
Hi @Perni1984,

Added a ISC license in `package.json`, feel free to use it in any way you'd like - and if you need any help to set it up you can reach me here or at oskar.ahlroth@gmail.com.
